language: node_js
node_js:
  - "4"
sudo: false
cache:
  directories:
    - node_modules
    - core/client/node_modules
    - core/client/bower_components
env:
  global:
    - GHOST_NODE_VERSION_CHECK=false
    - TEST_SUITE=server
  matrix:
    - DB=sqlite3 NODE_ENV=testing
